---
# Build on Assurio's CI system, Drone

# At first run a `cargo check` which is faster than a full compile but catches any code or dependency errors
kind: pipeline
name: initial_check

platform:
  os: linux
  arch: amd64

steps:
- name: cargo check
  image: ${DOCKER_REGISTRY}/assurio-rust:linux-amd64-latest
  environment:
    RUSTFLAGS: "--deny warnings"
  commands:
    - cargo check --all-targets

---

kind: pipeline
name: build_linux_amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build and test
  image: ${DOCKER_REGISTRY}/assurio-rust:linux-amd64-latest
  environment:
    RUSTFLAGS: "--deny warnings"
  commands:
    - cargo build
    - cargo test
