language: rust
dist: bionic

os:
- linux
- osx

rust:
  - stable

install:
  - rustup component add rustfmt
  - rustfmt -V
  - rustup component add clippy
  - cargo clippy --version

script:
  - .travis/lints.sh
  - .travis/tests.sh
